### PR TITLE
Fixed the navbar for mobile sccreen

### LINKED ISSUE #598: NOT GOOD for mobile screen
### Describe the feature

image

### Add ScreenShots

It should be made to look proper spacing and uniform design to have a better professional look

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Utsavladia**
## Related Issue
Fixes #598 

## Description
[Please include a brief description of the changes or features added]

## Type of PR
- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
Update branch

**Comment by Utsavladia** [comment]
@SUGAM-ARORA 
Resolved ✅

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Resolved ✅

Please update again

**Comment by Utsavladia** [comment]
@SUGAM-ARORA 
Updated ✅

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
