### PR TITLE
Enhancement done in the statistics section.

### LINKED ISSUE #439: Feat: Enhancement in the statistics page.
### Describe the feature

I think if the statistics section had border-bottom , placeholder in every text item so it would have better UI and also it is not aligned properly. I would also like to make it responsive.
Please Assign me this issue with the level and label of GSSOC'24.

### Add ScreenShots

before:
image

after:
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by agrwal697**
## Related Issue
Fixes #439

## Description
The Contact section had border-bottom in every text item so it would have better UI .

## Type of PR

-  Bug fix

## Screenshots / videos (if applicable)
image

## Checklist:
- [] I have performed a self-review of my code
- [] I have read and followed the Contribution Guidelines.
- [] I have tested the changes thoroughly before submitting this pull request.
- [] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@agrwal697 Your branch is not up to date. Moreover if possible have some more enhancements.

**Comment by agrwal697** [comment]
image


update in the branch is done.

**Comment by SUGAM-ARORA** [comment]
> image
> 
> update in the branch is done.

@agrwal697 Need to update branch once again

**Comment by agrwal697** [comment]
image


done sir.

**Comment by SUGAM-ARORA** [comment]
> image
> 
> done sir.

Process is correct. Need to do it again as someone else had done it earlier

**Comment by agrwal697** [comment]
again changes are done .

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
