### PR TITLE
Fixed the footer sizing for all sizes to look uniform

### LINKED ISSUE #372: Fix Footer for Tablet screen 768 px
### Describe the feature

Footer should have uniform desing on all screen sizes so should be fixed for the tablet screen also 

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Utsavladia**
## Related Issue
Fixes #372 

## Description
Fixed the Footer by making the navbar stay in page and fit to page size

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Utsavladia Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md) for branch update

**Comment by Utsavladia** [comment]
@SUGAM-ARORA 
Done

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Utsavladia Still need to update branch

**Comment by Utsavladia** [comment]
@SUGAM-ARORA 
Done again

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Done again

Need to do again since someone else has done it earlier

**Comment by Utsavladia** [comment]
@SUGAM-ARORA 
merged and resolved conflicts.

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
