### PR TITLE
Made Sign-Out button Functional

### LINKED ISSUE #574: BUG: Making Sign-out button functional
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

On clicking the sign-out button, it should show a pop-up showing "Successfully signed out".

Sign-out

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by AkshitGarg24**
Fixes #574 

The Sign-Out button is now functional. After clicking the sign-out button, it will show a pop-up to confirm whether the user wants to sign-out or not. After clicking Yes, it will show another pop-up, showing "Successfully Signed Out".

https://github.com/user-attachments/assets/6a831e1b-133b-44fb-a151-740463745d4b

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
Branch update.

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 There is failure

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA Fixed that problem.

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
