### PR TITLE
fix: added transition effect

### LINKED ISSUE #478: BUG: Hover effect is not working properly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently the hover effect in footer of contact page  ``section-title`` doesnt have proper hover effect like links inside links container 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by upsaurav12**
## Related Issue
Fixes #478

## Description
[Please include a brief description of the changes or features added]
This issue was fixed by using ``transition`` property on css 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by upsaurav12** [comment]
@SUGAM-ARORA kindly review this issue

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@upsaurav12 Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by upsaurav12** [comment]
Do i need to resolve merge conflits?

**Comment by SUGAM-ARORA** [comment]
> Do i need to resolve merge conflits?

Yes.

**Comment by SUGAM-ARORA** [comment]
> @upsaurav12 Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

Follow these steps

**Comment by upsaurav12** [comment]
image
it doesnot have any ``update option``

**Comment by upsaurav12** [comment]
should i delete my commit ? ?

**Pull request closed without merging**
