### PR TITLE
Fix Overlapping of Feedback button and Scroll to top buttons 

### LINKED ISSUE #532: BUG: Feedback button and Scroll to top buttons are Overlapping
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hey @SUGAM-ARORA 

The Feedback button and Scroll to top buttons are Overlapping

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Related Issue
- Fixes #532 

## Description

image

## Type of PR

- [x] Bug fix
- [x] Feature enhancement

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@MastanSayyad Update branch

**Comment by MastanSayyad** [comment]
@SUGAM-ARORA Branch updated

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
Need to do branch update again

**Comment by MastanSayyad** [comment]
@SUGAM-ARORA Done the update

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Done the update

Sorry but need to update again. Merge is done on first come first serve basis

**Comment by MastanSayyad** [comment]
@SUGAM-ARORA Its fine I can understand! Update is done!

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
