### PR TITLE
Added login and sign up functionality

### LINKED ISSUE #338: Feat: link login and sign up functionality to frontend
### Describe the feature

the backend contains logic of login and sign up. We should link them to allow users to actually login.

### Add ScreenShots

NA.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by divyansh-2005**
## Related Issue
Fixes #338 

## Description
Added login and sign up functionality to frontend

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
firstly, start backend. ref README of backend
then, start fronted 
and signup then login

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@divyansh-2005 Shouldn't after login it should direct to the main page?

**Comment by divyansh-2005** [comment]
changes done.
kindly review and can the level be increased.

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@divyansh-2005 Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md) for branch updation

**Comment by divyansh-2005** [comment]
@SUGAM-ARORA I have created a new pr #384 with a new and updated branch

**Pull request closed without merging**
