### PR TITLE
Fixes #80

### LINKED ISSUE #80: Add Hover Effect with Transition on Cards
The cards on the website currently lack a hover effect, which makes the user experience less engaging. To improve the visual appeal and interactivity of the website, I will implement a scaling effect on the cards when they are hovered over, using CSS transitions. This will make the website more dynamic and visually appealing. Kindly label this issue and assign this issue to me.
Screenshot 2024-05-17 011624

### PR DESCRIPTION
**Pull request by AkshitGarg24**
The following changes are made to the project:-

1.  The cards have been scaled to larger sizes, and their background colors have been changed to a darker shade to highlight the hovering effects. A video demonstrating this has been attached.  

https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/fb0ae6aa-2d83-4a76-be83-2e244db4e38f

2. Hovering effects have also been added to the buttons on the cards. A video demonstrating this is included. 

https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/74ba1581-fc16-4548-a73d-d021c6383571

3. When hovering over the images on the cards, the title of the post will be displayed. This is demonstrated in the attached video.  

https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/03f5ad67-348f-4081-9a99-c4565b4f00b8

 
ScreenShot

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24  Kindly add the issue number . 
Like this 
Fixes #Issue_number

**Comment by AkshitGarg24** [comment]
Fixes #80

**Review by SUGAM-ARORA — APPROVED** [review]
Looks good

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA Request you to please add my name in the Assignees section.

**Pull request merged**
