### PR TITLE
Resolved Alignment Issue

### LINKED ISSUE #268: Alignment issue
Previously the page was aligned perfectly .But now it has some alignment issues
Earlier : 
Screenshot (2)
Now :
Screenshot (4)

### PR DESCRIPTION
**Pull request by Sneha0019**
## Related Issue
Fixes #268 

## Description
So basically, I was assigned to resolve the issues of Alignment as same it was earlier. Like added flex, made changes in main_img height
 So I changed alignment of card and the statistics points from blue to red, also increased the fontWeight of heading "Statistics".
 Similarly, I made changes in the Top contributor part by making color of font from blue to red as required.
Overall, main changes were in container.css file of the project.

## Type of PR
- [X] Feature enhancement

## Screenshots / videos (if applicable)
Screen Recording - 
https://github.com/SUGAM-ARORA/UniCollab/assets/112338459/15f57da6-be56-4314-b596-e473ad0dc160

Screenshot of changes made in main page
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Sneha0019  Just do branch updation. 
Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.sh)

**Comment by Sneha0019** [comment]
All the branches are up-to-date 
image

And the changes are live in deployed website on vercel 
image

**Comment by SUGAM-ARORA** [comment]
@Sneha0019 Firstly go to your cloned github repo and update the branch . Then  use the above commands

**Comment by Sneha0019** [comment]
I have done the changes as required and update the branch!

image

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Sneha0019 Still branch not up to date. Follow the following steps : 
1) Go to the cloned  github repo on browser and then click on sync fork and update branch . sample i have shared below
image
2) after doing this now follow the steps

**Comment by Sneha0019** [comment]
Thank you so much for guiding me I have done the changes!

Step 1:-
image

Step 2:-
image

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by Sneha0019** [comment]
Thank you!

**Pull request merged**
