### PR TITLE
[FIXES #138} Implemented Blog Page

### LINKED ISSUE #138: [FEATURE] Implementing a 'Blog' Page.
In the footer when we click on 'Blog' section, it takes us to blank page. I would like to create a blog page where users post their blogs. 
Request you to assign this task to me under GSSoC '24

### PR DESCRIPTION
**Pull request by yashmandi**
https://github.com/SUGAM-ARORA/UniCollab/assets/132436131/408b9f39-ccd5-4989-917c-722c25c466e1

FIXES #138

### CODE REVIEW

**Review by SUGAM-ARORA — APPROVED** [review]
Great work

**Comment by SUGAM-ARORA** [comment]
Level changed from 2 to 3

**Comment by Ojas-Arora** [comment]
@yashmandi How to make video like this?

**Comment by yashmandi** [comment]
> @yashmandi How to make video like this?
> 

i record the screen using snipping tool

**Pull request merged**
