### PR TITLE
Added Icons to Footer

### LINKED ISSUE #441: Add Icons To Footer
### Describe the feature

Hello Project Admin
I would like to add icons to Footer to make website look attractive 

### Add ScreenShots

IMG_20240706_123501

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Added Icons to Navbar - 
Fixes #441 
Kindly Please go through this PR @SUGAM-ARORA 

plpl

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@sailaja-adapa Update branch

**Comment by sailaja-adapa** [comment]
Yeah ok @SUGAM-ARORA

**Comment by SUGAM-ARORA** [comment]
@sailaja-adapa Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by sailaja-adapa** [comment]
Yeah okk @SUGAM-ARORA I will update you by this evening

**Comment by sailaja-adapa** [comment]
@SUGAM-ARORA is it okay now??

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA is it okay now?? I Updated Branch Now

Need to update again

**Comment by sailaja-adapa** [comment]
@SUGAM-ARORA  I Updated it please look into it

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
