### PR TITLE
Feat: News letter section added

### LINKED ISSUE #406: Feat: Adding subscribe newsletter section
### Describe the feature

Adding subscribe newsletter section

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
## Related Issue
Fixes #406 
## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
hi @SUGAM-ARORA review the PR

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@RamakrushnaBiswal Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by RamakrushnaBiswal** [comment]
@SUGAM-ARORA review the PR

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@RamakrushnaBiswal Need to update branch once again. ANd if possible put the subscribe newsletter below description of unicollab in footer or somewhere else. since the footer is not looking too good with this

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@RamakrushnaBiswal Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by RamakrushnaBiswal** [comment]
@SUGAM-ARORA review the PR

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
