### PR TITLE
Implement Popular Page to Highlight Trending Content

### LINKED ISSUE #577: Feat: Implement Popular Page to Highlight Trending Content
### Describe the feature

@SUGAM-ARORA I want to add the popular section in the website. Kindly assign me this issue.

### Add ScreenShots

Screenshot (2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## Related Issue
Fixes #577 

## Description
@SUGAM-ARORA I have made the changes for implementing the Popular page with the Feed. Kindly review this.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Issue assigned to you

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA I think this issue to be of level 3. Kindly please review.

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA Sir I thik this issue to be of level 3. Kindly review this.

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Sir I think this issue to be of level 3 due to implemetaion of a new page for the popular cards and the creation of new cards for the popular page and also making them sure that the cards look same like that in the feed page. Also I have added the working of the toggle in All, type by and sort buttons also. Kindly review this.

Ya sure let me review this.

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Level changed. Actually I didn't consider the toggle in all , type and sort button . Moreover making sure that card quality remains same is great too. I missed it my mistake..

**Pull request merged**
