### PR TITLE
Feature Added : Implemented Responsive "Read More" Button with Dynamic Project Details #181

### PR DESCRIPTION
**Pull request by mohangolakoti**
## Related Issue
Feature Added #181 

## Description
Hello @SUGAM-ARORA,
I have implemented the "Read More" button functionality. It now dynamically navigates to another page to display detailed information about the respective project. Additionally, the new page is fully responsive and ensuring that the color palette matches the page.

## Type of PR
- [X ] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/SUGAM-ARORA/UniCollab/assets/116739999/7c3e30dd-0f71-4877-87bc-11370e548db6

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.

## Additional context:
Could you please add the "level2" label to the pull request. I've completed more than the level 1 requirements by adding responsiveness and implementing dynamic display of project details.

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@mohangolakoti Great changes. 
Just do one thing branch updation. 
Try the following steps:

git checkout main
git pull
git checkout
git merge main
[ ... resolve any conflicts ... ]
git add [files that were conflicted]
git commit
git push

**Comment by mohangolakoti** [comment]
@SUGAM-ARORA iam resolved the conflicts please check

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by mohangolakoti** [comment]
Thank you for merging the pull request.

**Pull request merged**
