### PR TITLE
made create account page responsive

### LINKED ISSUE #280: bug: Create account page is not responsive
Screenshot 2024-06-11 201642
Screenshot 2024-06-11 201702
The create account page is not responsive in mobile as well as laptop screens .Kindly assign this task to me under GSSoC'24

### PR DESCRIPTION
**Pull request by Jagpreet153**
## Related Issue
Fixes #280

## Description
I have made create account page responsive for all screens

## Type of PR
- [x] Bug fix

## Screenshots / videos (if applicable)
Screenshot 2024-06-13 193622

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Kindly assign this pr to me and add relevant labels

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@Jagpreet153  Just do branch updation. 
Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.sh)

**Comment by Jagpreet153** [comment]
@SUGAM-ARORA Please check now

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Jagpreet153 This might look good for small screen but not much impressive for full screen

**Comment by Jagpreet153** [comment]
> @Jagpreet153 This might look good for small screen but not much impressive for full screen

The css is same as before I have only made it responsive for small screens . 
For large screen it looks like this .
Screenshot 2024-06-16 012932

**Review by SUGAM-ARORA — APPROVED** [review]
@Jagpreet153 Not much impressive but i think this is what I have to accept at the moment. there is no other way

**Pull request merged**
