### PR TITLE
color coordination issue

### LINKED ISSUE #269: Color coordination issue
Color code is not in sync witht the whole website . Need to have same color coordination for all. Eg: Login page has different color set , main page differet, contact and other features different

### PR DESCRIPTION
**Pull request by supriyagaut**
## Related Issue
Fixes #269 

I have completed this issue adding similar colors on the other pages as the main page and recreating a register page.
kindly merge my Pull Request adding level under GSSOC'24

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

Uploading Recording 2024-06-15 213835 unicollab_about us.mp4…

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@supriyagaut Update the branch

**Comment by supriyagaut** [comment]
@SUGAM-ARORA sorry I don't understand how to update the branch.

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@supriyagaut Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by supriyagaut** [comment]
@SUGAM-ARORA 
Screenshot 2024-06-19 160009
Screenshot 2024-06-19 160103
I am done from my side can you please check once and let me know..

**Review by SUGAM-ARORA — APPROVED** [review]
Great work @supriyagaut .

**Pull request merged**
