### PR TITLE
Random Developer Names with Profile Pages #204

### LINKED ISSUE #204: Enhancing User Engagement with Random Developer Names and Profile Pages
Hello @SUGAM-ARORA,
I have implemented dynamic display of developer names and their information in place of placeholder "Abc".  Additionally, clicking on "View Profile" now navigates to a separate page displaying the respective developer's profile.

The use of random names in place of "Abc" on the web page serves to create a more dynamic and realistic user experience. By incorporating actual developer names, users can better visualize the team behind the project, fostering a sense of authenticity and professionalism. 

Screenshot:
devs-feat

Please assign me this issue. I have successfully added the feature to dynamically display developer names on the web page and implemented profile pages for each developer.

### PR DESCRIPTION
**Pull request by mohangolakoti**
## Related Issue
Fixes #204

## Description
Hello @SUGAM-ARORA,
I have solved the issue and made the following enhancements:
-Added dynamic display of developer names on the web page.
-Implemented profile pages for each developer.
-Added effective profile pictures.
-Ensured responsiveness of the profile pages.
-Updated profile pictures on the Read More page.
-Added different roles and about sections for developer profiles.

## Type of PR
- [X] Feature enhancement

## Screenshots / videos (if applicable)

https://github.com/SUGAM-ARORA/UniCollab/assets/116739999/b0b0a094-ca07-436e-aff9-e360b7425d16

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.

## Additional context:
Could you please add the "level2" label to the pull request, I've completed more than the level 1 requirements by adding responsiveness, profile pictures, and updated profile pictures on the Read More page.

### CODE REVIEW

**Comment by mohangolakoti** [comment]
Hey @SUGAM-ARORA, Please check this PR

**Comment by mohangolakoti** [comment]
@SUGAM-ARORA kindly review this PR, and if there are any changes to be made do let me know.

**Comment by SUGAM-ARORA** [comment]
@mohangolakoti Just update branch

**Comment by mohangolakoti** [comment]
Hey @SUGAM-ARORA, Iam updated the branch and add profiles for remaining 6 projects. Please review the PR

**Comment by mohangolakoti** [comment]
> @mohangolakoti Just update branch

Iam Updated the branch please review the PR

**Comment by mohangolakoti** [comment]
I am updated the branch please review the PR and let me know if it
needs any changes

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@mohangolakoti Just do branch updation. 
Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.sh)

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
