### PR TITLE
adding services

### PR DESCRIPTION
**Pull request by aasthakourav20**
Fixes: #154 
- [x ] Feature enhancement

Added Services Section & enhanced about_us . 
Screenshot (230)
Screenshot (231)

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
Closes: #154

### CODE REVIEW

**Comment by aasthakourav20** [comment]
Hey @SUGAM-ARORA , changes are done . Kindly review

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@aasthakourav20 These changes look good. Just do one thing pull the main so that updates changes are there in code

**Comment by aasthakourav20** [comment]
> @aasthakourav20 These changes look good. Just do one thing pull the main so that updates changes are there in code

I'm facing some problems while doing this , can you please help me with the commands to be used .

**Comment by aasthakourav20** [comment]
> @aasthakourav20 These changes look good. Just do one thing pull the main so that updates changes are there in code

Hey @SUGAM-ARORA , Please reply  for the issue .

**Comment by aasthakourav20** [comment]
Hey @SUGAM-ARORA , I don't know  what happened exactly but while you merged  someone's new footer , we can't see any services , contact , blogs & FAQs section's routes in the footer . Kindly check it

**Pull request merged**
