### PR TITLE
Fix "Cursor-Trail" Effect "Synchronization" Issue

### LINKED ISSUE #370: BUG 🐞: "Glitchy Cursor" Trail Effect and "Asynchronize Cursor Movement"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hey @SUGAM-ARORA 

The current implementation of the cursor trail effect on the website is experiencing significant issues. 
- The cursor and the trail effect are not synchronized, 
- leading to the cursor moving to one location while the trail effect shows up somewhere else. 
- Buttons and links are unable to click
- This results in a glitchy and irritating user experience. 

https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/23fa3e94-13e6-42d5-bc28-0257c087ec8d

This issue impacts the overall user experience negatively and needs to be addressed as a priority.

The goal of this issue is to **fix this synchronization problem** and **ensure the cursor movement is smooth** with an appropriate trail effect.

## Solution

- Review and update the JavaScript code responsible for the cursor trail effect.
- Ensure the event listeners for mouse movements are correctly implemented and optimized.
- Test the synchronization of the cursor and the trail effect across different browsers and devices.
- Implement any necessary performance improvements to make the cursor movement and trail effect smooth.

Please assign me this issue!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Description

Hey @SUGAM-ARORA  | 
Fixes #370 

The trail effect behind the cursor was not syncing correctly, especially near the footer area of the website.
I have Fixed  **"Cursor-Trail"** Effect **"Synchronization"** Issue

### Changes Made
- Adjusted the mouse event listener to correctly capture cursor position relative to vertical scroll.
- Changed trail effect color to `#ff21bc` Matching to the website design theme for consistency and visibility.
- Ensured smooth synchronization of trail effect with cursor movement.

https://github.com/SUGAM-ARORA/UniCollab/assets/101971980/8fbcf113-1885-4d6e-a90c-628e269d2572

## Type of PR

- [x] Bug fix
- [x] Feature enhancement

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@SUGAM-ARORA Branch update completed

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Branch update completed

Need to do again since someone else has done it earlier

**Comment by MastanSayyad** [comment]
@SUGAM-ARORA Branch update done

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
