### PR TITLE
follow and upload features added

### PR DESCRIPTION
**Pull request by mtg718**
follow and upload features added #30

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
Your updation is good but it is not in line with the latest project updates.

**Comment by mtg718** [comment]
Hello @SUGAM-ARORA ,then what I supposed to change , please tell me

**Comment by mtg718** [comment]
Hello @SUGAM-ARORA ,please merge my PR.

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@mtg718 I feel your branch is not up to date with the latest changes.
No footer , no settings page is there

**Comment by SUGAM-ARORA** [comment]
@mtg718 Try the following steps:
git checkout main
git pull
git checkout
git merge main
[ ... resolve any conflicts ... ]
git add [files that were conflicted]
git commit
git push

**Comment by mtg718** [comment]
@SUGAM-ARORA , please merge the changes now I had created a new branch mohit_upload with all the changes correctly.

**Pull request closed without merging**
