### PR TITLE
Enhanced footer: Added Services section

### PR DESCRIPTION
**Pull request by aasthakourav20**
Fixes: #135 
- [x ] Feature enhancement

## Checklist:
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.

Closes : #135 
Screenshot (227)
Screenshot (226)

### CODE REVIEW

**Comment by aasthakourav20** [comment]
Hey @SUGAM-ARORA , Changes are done . please review

**Review by SUGAM-ARORA — APPROVED** [review]
Looks good

**Comment by SUGAM-ARORA** [comment]
@aasthakourav20 Make sure to update branch. Recently I have merged blog page but now it is not there . Take care from next time

**Comment by SUGAM-ARORA** [comment]
I have removed your updates . If you want to do the updates again then raise issue and PR . Points will not be assigned in that as I have assigned here

**Pull request merged**
