### PR TITLE
[Bug] : button accessable fix

### LINKED ISSUE #25: [Bug] : Button Accessability
- If the right side `Top contributor` containers button are hover not pointing.
- If the button we will hover that cannot be responding. 
Screenshot from 2024-05-11 18-58-22

### PR DESCRIPTION
**Pull request by sivaprasath2004**
#25  
- If the `Button Accessable` problem has been solved..
- please merge it..
### Before

Screenshot from 2024-05-11 18-58-22

### After

Screenshot from 2024-05-14 08-57-22

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
@SUGAM-ARORA i will finished it....

**Comment by SUGAM-ARORA** [comment]
@sivaprasath2004 Have you made all the changes?

**Comment by sivaprasath2004** [comment]
@SUGAM-ARORA yes please merge it... Problem was fix

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
