### PR TITLE
Adding Facebook Authentication

### LINKED ISSUE #547: Feat: Adding Facebook Authentication
### Describe the feature

@SUGAM-ARORA I want to add Facebbok Authentication using Firebase. Kindly assign me this issue.

### Add ScreenShots

Screenshot 2024-07-14 181023

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## Related Issue
Fixes #547 

## Description
@SUGAM-ARORA Ihave added the facebook Authentication as well as improved the styling in some pages. Make sure to allow authentication of Facebook in Firebase. Kindly review this.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Great work. Make sure to connect all the social media with firebase. Likewise I will do the authentication from the portal

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA Sir as per discussed earlier I have already done the authentication for Github, Phone and Facebook. Moreover I am in the process of raising the PR of twitter, microsoft. Just want to clarify from you whether to  do authentication for LinkedIn also or not?

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Sir as per discussed earlier I have already done the authentication for Github, Phone and Facebook. Moreover I am in the process of raising the PR of twitter, microsoft. Just want to clarify from you whether to do authentication for LinkedIn also or not?

If possible then you can include Linkedin too. But ig firebase might not have Linkedin one directly. Might need to add external link

**Pull request merged**
