### PR TITLE
Made login page responsive for all devices

### LINKED ISSUE #380: BUG: Login Page is not Responsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The Login page is not able to work in mobiles or Tabs. I want to make the login page responsive for all devices which will add new look and feel for the website.
Screenshot 2024-06-24 085352
Screenshot 2024-06-24 085404
Screenshot 2024-06-24 085419
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by saketh-05**
## Related Issue
Fixes #380 

## Description
[Please include a brief description of the changes or features added]
Made few changes in login.css, login.js files and fixed issues and made login page responsive.

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/4b297924-6440-40c3-9387-fb75be074966

https://github.com/SUGAM-ARORA/UniCollab/assets/134281589/e787d221-ea69-4ec4-b01a-9dc61a0d4613

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@saketh-05 Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
.

**Comment by saketh-05** [comment]
@SUGAM-ARORA I had updated my branch. Please review my PR.

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
