### PR TITLE
Added Legal Pages

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #225 

I have added 3 Legal Pages - Privacy Policy, Terms and Conditions and Licensing. I have also made the pages responsive.

image

@SUGAM-ARORA can you please check and let me know if any changes are required?

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@Hemashree21 Just update the branch . Else good to go

**Comment by Hemashree21** [comment]
@SUGAM-ARORA I updated it

**Comment by SUGAM-ARORA** [comment]
@Hemashree21 update branch once again please

**Comment by Hemashree21** [comment]
@SUGAM-ARORA is it updated now?

**Comment by SUGAM-ARORA** [comment]
@Hemashree21 Yes up to date but now the connections with Legal pages is not there

**Comment by Hemashree21** [comment]
@SUGAM-ARORA I updated it

**Comment by SUGAM-ARORA** [comment]
@Hemashree21 Still branch not fully updated

**Pull request closed without merging**
