### PR TITLE
Added scroll progress bar

### LINKED ISSUE #471: 🌟 Feature: Add a Scroll "Progress Indicator Bar"
### Describe the feature

Hey @SUGAM-ARORA ,
I want to add a "Scroll Down Progress Bar"

This feature adds a scroll down progress bar to the website, which visually indicates the user's progress as they scroll down the page.
The progress bar enhances user experience by providing a clear visual cue of their location on the page and how much content remains to be viewed.

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Tejashri-Taral**
Hey @SUGAM-ARORA  ,
issue closes #471

I have added the Scroll down progress bar in All pages of the website

## Type of PR

- [x] Feature enhancement

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.

Please take a look and review it.

### CODE REVIEW

**Comment by Tejashri-Taral** [comment]
@SUGAM-ARORA ,Please take a look and review it

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Tejashri-Taral Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by Tejashri-Taral** [comment]
@SUGAM-ARORA ,Please check now

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
