### PR TITLE
SEO tags added

### LINKED ISSUE #358: Feat: Make website SEO friendly
### Describe the feature

I would like to make the website SEO friendly by adding the appropriate meta tags and keywords.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by chaanakyaaM**
## Related Issue
Fixes #358 

## Description
[Please include a brief description of the changes or features added]

I have added the appropriate tags to make the website SEO friendly

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

Kindly let me know if there are any changes to be made.

### CODE REVIEW

**Comment by chaanakyaaM** [comment]
@SUGAM-ARORA  kindly review this PR.

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@chaanakyaaM Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by chaanakyaaM** [comment]
image

**Comment by SUGAM-ARORA** [comment]
> image
> 
> i have followed the steps from that file and this is the result im getting...

@chaanakyaaM Please update branch once again as someone has already done it earlier

**Comment by SUGAM-ARORA** [comment]
Moreover the process which you followed for branch update earlier was correct as after those steps a fresh deployment came

**Comment by chaanakyaaM** [comment]
image


I couldn't open the image.

**Comment by chaanakyaaM** [comment]
Im so sorry for the confusion.
Is this it?
image

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by SUGAM-ARORA** [comment]
@chaanakyaaM Check the branch if there is any update left. There are conflicts shown . You can once again do the branch update

**Comment by chaanakyaaM** [comment]
Merge conflict resolved.

**Comment by SUGAM-ARORA** [comment]
> Merge conflict resolved.

Need to update again as someone else has already done it earlier

**Comment by chaanakyaaM** [comment]
Merge conflicts resolved.

**Comment by chaanakyaaM** [comment]
Kindly review this PR.

**Comment by chaanakyaaM** [comment]
image

**Pull request merged**
