### PR TITLE
border and box shadow

### LINKED ISSUE #373: Adding background border and shadow on the service page also adding the heading of services.
Screenshot 2024-06-23 130947

@SUGAM-ARORA  I want to add a background border and background shadow and also add a services heading to enhance the website.
kindly assign me this issue under GSSOC'24. I would like to work on this.

### PR DESCRIPTION
**Pull request by supriyagaut**
## Related Issue
Fixes #373 

## Description
I have added the border and box-shadow on the div which enhance the overall service page also it matches the website color coordination. kindly merge my pull request under GSSOC'24

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot 2024-06-26 153911

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@supriyagaut Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by supriyagaut** [comment]
@SUGAM-ARORA kindly recheck the I have updated

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA kindly recheck , I have updated

@supriyagaut You need to do it again as someone has already done it earlier

**Comment by supriyagaut** [comment]
> > @SUGAM-ARORA kindly recheck , I have updated
> 
> @supriyagaut You need to do it again as someone has already done it earlier

@SUGAM-ARORA what i have to do it i dont understand

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
