### PR TITLE
Made several changes and fixed navbar responsiveness.

### PR DESCRIPTION
**Pull request by saketh-05**
## Related Issue
Issue no: #169 

## Description
Made changes to Container.css, Menu.css, Menu.js, TopContainer.js files. Implemented navbar correctly for mobile ,tab, etc. devices. This will fix most of the responsive navbar issues.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-05-30 205243
pic2
pic3
pic4

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
Impressive updates @saketh-05 . Just one thing to do more - Update the branch with the latest updates

git checkout main
git pull
git checkout
git merge main
[ ... resolve any conflicts ... ]
git add [files that were conflicted]
git commit
git push

**Comment by saketh-05** [comment]
@SUGAM-ARORA I have done what u said i.e. updating my branch with the latest updates from the main branch.

**Comment by saketh-05** [comment]
@SUGAM-ARORA I have updated my branch, please go through my pull request, also I want to work on issue #170 please assign that to me as I have completed this issue

**Comment by saketh-05** [comment]
@SUGAM-ARORA Please tell me if I should make any more changes. I will respond quickly. It took me lot time and effort to learn, analyse the issue and fix it 🥲.

**Review by SUGAM-ARORA — APPROVED** [review]
Great work @saketh-05

**Comment by SUGAM-ARORA** [comment]
@saketh-05 Sorry for the delay from my side.  Generally I take max 1-2 days to merge PR's. Moreover if there is a delay from my side in assigning any issue then you can start the work from your end.

**Pull request merged**
