### PR TITLE
Add "Back To Home Button" in "Legal and Missing" Pages

### LINKED ISSUE #343: Add "Back To Home Button" on "Legal Pages"
### Describe the feature

Hey @SUGAM-ARORA 

There is a **"Back to Home"** button present on all pages of the website except for the legal pages. 
The legal pages, including **Privacy Policy, Terms and Conditions, and Licensing**, lack this button, in which users might find it inconvenient to navigate back to the homepage.

### Add ScreenShots

image

I would like to Add a "Back to Home" button on the following legal pages to improve navigation and user experience:

- Privacy Policy
- Terms and Conditions
- Licensing

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hey @SUGAM-ARORA | issue closes #343 

I have added back to home button in all missing pages to ensure user is convenient to navigate back to the homepage.
The Pages are:
- Privacy Policy
- Terms and Conditions
- Licensing
- Careers Page

## Type of PR

- [X] Feature enhancement

## Screenshots / videos (if applicable)

- **Privacy Policy**

image

- **Terms and Conditions**

image

- **Licensing**

image

- **Careers Page**

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@SUGAM-ARORA please merge this PR,thank you!

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@MastanSayyad Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md) for branch updation

**Comment by MastanSayyad** [comment]
@SUGAM-ARORA I've updated the Branch

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
