### PR TITLE
Added the feature to auto comment on pr merged

### LINKED ISSUE #129: Auto Commenting when a PR is merged
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
## Related Issue
Fixes #129 

## Description
I have added auto-comment-on-pr-merge.yml in .github/workflows directory. This file will add the feature of auto commenting when a pr is merged.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by suhanipaliwal** [comment]
Please add the label of level1 and gssoc on this pull request and assign me this pr as per gssoc guidelines.

**Comment by suhanipaliwal** [comment]
Please add the label of level1

**Comment by SUGAM-ARORA** [comment]
@suhanipaliwal Gssoc has only asked to not give level to any workflows PR.

**Comment by suhanipaliwal** [comment]
> @suhanipaliwal Gssoc has only asked to not give level to any workflows PR.

I don't think there is any such instruction. Workflow PRs should just not be given any level more than level1.

**Comment by SUGAM-ARORA** [comment]
> > @suhanipaliwal Gssoc has only asked to not give level to any workflows PR.
> 
> I don't think there is any such instruction. Workflow PRs should just not be given any level more than level1.

@suhanipaliwal Let me confirm.

**Pull request merged**
