### PR TITLE
Fix dropdown alignment issue (#113)

### PR DESCRIPTION
**Pull request by SeanAverS**
## Related Issue
None

## Description
- Fixed notification dropdown from aligning to the right by removing the translate property
- Hide the dropdown on page load 
- Toggle dropdown visibility using the top right arrow 

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@SeanAverS Not looking good. Dropdown is static here.

**Comment by SeanAverS** [comment]
Would you want me to hide the dropdown on page load and show it when the user clicks the arrow on the top right(next to their profile name)?

**Comment by SeanAverS** [comment]
Hi @SUGAM-ARORA, thanks for your feedback.

This PR specifically addresses the dropdown alignment issue (#113). For the new feature, could you please create a new issue? I'll be happy to work on it separately.

**Comment by SUGAM-ARORA** [comment]
> Hi @SUGAM-ARORA, thanks for your feedback.
> 
> This PR specifically addresses the dropdown alignment issue (#113). For the new feature, could you please create a new issue? I'll be happy to work on it separately.

@SeanAverS If you fix this in this I would change this to level2. Else if you want a separate issue for this I am okay with that too.

**Comment by SeanAverS** [comment]
I will fix it in this issue 👍

**Pull request closed without merging**
