### PR TITLE
Added Logo click navigation

### LINKED ISSUE #293: FEATURE : Logo Click Navigation
Linking the logo to home page.
 It's a standard practice in web design and user experience to have the logo of a website or application act as a clickable link that takes users back to the main home page. This behavior is expected and intuitive for most users, as they associate the logo with the primary landing or home page of the website.
 This feature makes the website more user friendly and also enhances the overall experience of the user as well. 
 I'm a GSSoC'24 contributor, with a strong understanding of web development and I want to work on this. So can you please assign it to me @SUGAM-ARORA

### PR DESCRIPTION
**Pull request by sanskriti-lal**
## Related Issue
Fixes #293 

## Description

 Integrated the logo with home page link by defining the handleLogoClick function in the Menu.js component. This function is responsible for handling the click event on the logo. When the logo is clicked, the handleLogoClick function uses window.location.assign to navigate the user to the main page URL (https://uni-collab.vercel.app in this case). By setting the onClick event of the logo ( element) to trigger the handleLogoClick function, clicking the logo results in a seamless redirection to the specified URL, enhancing the overall navigation experience within the application.

## Type of PR

- [ ] Bug fix
- [ X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/SUGAM-ARORA/UniCollab/assets/165655543/08285637-7eeb-465d-a0e9-06c3c0668ca0

## Checklist:
- [X ] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
None

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@sanskriti-lal Just update the branch . Else great work

**Comment by sanskriti-lal** [comment]
Hey, it's saying that it's already up to date. Also @SUGAM-ARORA can you please assign labels.

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@sanskriti-lal Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by sanskriti-lal** [comment]
Done, @SUGAM-ARORA can you please check it once. Also please assign the mentioned GSSoC labels:)

**Comment by SUGAM-ARORA** [comment]
@sanskriti-lal Still branch not  updated

**Comment by sanskriti-lal** [comment]
Screenshot 2024-06-19 at 11 31 26 PM

can you please check once again

**Comment by SUGAM-ARORA** [comment]
After  this do the second  step

**Comment by sanskriti-lal** [comment]
Hey @SUGAM-ARORA , I've updated the branch by following both the steps can you please check it once again. Also sorry for the inconvenience

**Pull request closed without merging**
