### PR TITLE
made static navabr of top contributor

### LINKED ISSUE #465: Make Topcontributor static
### Describe the feature

when we scroll the top contributor list header also gets scroll its should be static 

### Add ScreenShots

https://github.com/SUGAM-ARORA/UniCollab/assets/146806880/c154ade6-3d34-473e-90ba-515a6862fb6d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Ketanop321**
Fixes #465 

## Description
Made the top contributor header static
## Type of PR

- [✅ ] Feature enhancement

## Screenshots / videos (if applicable)
image

## Checklist:
- [ ✅] I have performed a self-review of my code
- [✅ ] I have read and followed the Contribution Guidelines.
- [✅ ] I have tested the changes thoroughly before submitting this pull request.
- [ ✅] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Ketanop321 Just update branch else good to go

**Comment by Ketanop321** [comment]
> @Ketanop321 Just update branch else good to go

@SUGAM-ARORA can you check now

**Comment by SUGAM-ARORA** [comment]
> > @Ketanop321 Just update branch else good to go
> 
> @SUGAM-ARORA can you check now

No update

**Comment by Ketanop321** [comment]
> > > @Ketanop321 Just update branch else good to go
> > 
> > @SUGAM-ARORA can you check now
> 
> No update
@SUGAM-ARORA 
Can u please guide me how to do it, I have done it but I think its not working🙏🙏😭

**Comment by SUGAM-ARORA** [comment]
@Ketanop321  Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md). This will guide  you how to do branch update.

**Comment by SUGAM-ARORA** [comment]
> > > > @Ketanop321 Just update branch else good to go
> > > 
> > > 
> > > @SUGAM-ARORA can you check now
> > 
> > 
> > No update
> > @SUGAM-ARORA
> > Can u please guide me how to do it, I have done it but I think its not working🙏🙏😭

Maybe git push is left only

**Comment by Ketanop321** [comment]
@sumg

> > > > > @Ketanop321 Just update branch else good to go
> > > > 
> > > > 
> > > > @SUGAM-ARORA can you check now
> > > 
> > > 
> > > No update
> > > @SUGAM-ARORA
> > > Can u please guide me how to do it, I have done it but I think its not working🙏🙏😭
> 
> Maybe git push is left only

@SUGAM-ARORA  can you check this out

**Pull request merged**
