### PR TITLE
Aligned the to-the-top button to center

### LINKED ISSUE #415: Feat: Centre aligned the To The Top Button
### Describe the feature

Have aligned the "To the top" button to center. Works fine in both PC and Mobile view and gives a clean look to the UI.

### Add ScreenShots
Current Website:
image
After Update:
featurepc
featuremobile

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by amandeeep02**
## Related Issue
Fixes #415 

## Description
Have aligned the to the top button to the center.
## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable):
image

image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@amandeeep02 Do branch update.

**Comment by amandeeep02** [comment]
> @amandeeep02 Do branch update.

My branch is already up to date.

**Comment by SUGAM-ARORA** [comment]
> > @amandeeep02 Do branch update.
> 
> My branch is already up to date.

Nhi hai update @amandeeep02

**Comment by SUGAM-ARORA** [comment]
@amandeeep02 Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by amandeeep02** [comment]
> @amandeeep02 Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

Abhi kar diya 👍

**Comment by amandeeep02** [comment]
Theek hua ki mai ek new Pull request create karu with the updated branch?

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by SUGAM-ARORA** [comment]
> Theek hua ki mai ek new Pull request create karu with the updated branch?

Not needed

**Pull request merged**
