### PR TITLE
Add My Projects and New Project pages

### PR DESCRIPTION
**Pull request by DharshiBalasubramaniyam**
## Related Issue
this pr fixes issue #172.

## Description
I have added a new menu item for view their own projects. 
I have created MyProjects.jsx which display the list of projects published.
I have created NewProject.jsx which display a form for uploading a new project.
I have added fields like, project name, repo link, description, image, and skills used. I have implemented validations for input fields as well.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/SUGAM-ARORA/UniCollab/assets/139672976/fb1fd977-44f0-4f5a-96e1-7acb50bb662a

Screenshot 2024-05-29 205804
Screenshot 2024-05-30 150526

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@DharshiBalasubramaniyam Update your branch with latest updates. If you face any problem then try these steps:

git checkout main
git pull
git checkout
git merge main
[ ... resolve any conflicts ... ]
git add [files that were conflicted]
git commit
git push

**Comment by DharshiBalasubramaniyam** [comment]
@SUGAM-ARORA I have updated the branch. Kindly please review my pr.

**Comment by SUGAM-ARORA** [comment]
@DharshiBalasubramaniyam Just do branch update once again . I will merge this then

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam Just do branch update once again . I will merge this then

done!

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
