### PR TITLE
Sign in sign out#516

### LINKED ISSUE #516: BUG: Improvment in Signin/Signup form in mobile view
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently the Sign-in/Sign-up page is not responsive for mobile view 

https://github.com/user-attachments/assets/24cea351-3a73-4a60-9c30-f62ca9b8fef4

Improvment in Sign-up/ Sign-in Form

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by upsaurav12**
## Related Issue
Fixes #516 
## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by upsaurav12** [comment]
i didnt even added json file (file that were causing merge conflicts) but still go

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@upsaurav12  Need to check  failure

**Comment by upsaurav12** [comment]
> @upsaurav12 Need to check failure

i have got 159 conflcts with json and yarn i dont know why i got added even i just added ``Login.css``

**Comment by SUGAM-ARORA** [comment]
> > @upsaurav12 Need to check failure
> 
> i have got 159 conflcts with json and yarn i dont know why i got added even i just added `Login.css`

Then the better option is to cut another branch and do the changes in it while making sure that branch is up to date

**Comment by upsaurav12** [comment]
How to do it ?

**Comment by upsaurav12** [comment]
> > > @upsaurav12 Need to check failure
> > 
> > 
> > i have got 159 conflcts with json and yarn i dont know why i got added even i just added `Login.css`
> 
> Then the better option is to cut another branch and do the changes in it while making sure that branch is up to date

Do you mean raising a new pr??

**Comment by SUGAM-ARORA** [comment]
> > > > @upsaurav12 Need to check failure
> > > 
> > > 
> > > i have got 159 conflcts with json and yarn i dont know why i got added even i just added `Login.css`
> > 
> > 
> > Then the better option is to cut another branch and do the changes in it while making sure that branch is up to date
> 
> Do you mean raising a new pr??

Yes

**Comment by upsaurav12** [comment]
but i have created 2nd PR not sure that new PR will not give this issue

**Comment by upsaurav12** [comment]
SORRY for creating multiple PR's it was due to 620 merge conflicts in package-lock.json

**Pull request closed without merging**
