### PR TITLE
Made website SEO friendly

### LINKED ISSUE #358: Feat: Make website SEO friendly
### Describe the feature

I would like to make the website SEO friendly by adding the appropriate meta tags and keywords.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by chaanakyaaM**
## Related Issue
Fixes #358 

## Description
[Please include a brief description of the changes or features added]

I have added the appropriate meta tags and links which helps the website to become SEO friendly.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

Kindly let me know if there are any changes to be made.

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@chaanakyaaM Just update the branch

**Comment by chaanakyaaM** [comment]
sry but i didn't understood.

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@chaanakyaaM Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by chaanakyaaM** [comment]
ok

**Pull request closed without merging**
