### PR TITLE
Done #201

### PR DESCRIPTION
**Pull request by GOURAVSINGH19**
## Related Issue
issue is search bar icon 
## Description
i add new Hook useRef for search btn on click it focus on search bar
## Type of PR

- [ ] Bug fix

## Screenshots / videos (if applicable)

https://github.com/SUGAM-ARORA/UniCollab/assets/120244528/9dc4bfef-a0c7-4e6a-8d22-b552c234c946

Thanks for assign me this issue...

### CODE REVIEW

**Comment by GOURAVSINGH19** [comment]
@SUGAM-ARORA done if there is any problem please tell me I will try to correct asap..

**Comment by GOURAVSINGH19** [comment]
@SUGAM-ARORA can you merge the problem

**Comment by SUGAM-ARORA** [comment]
@GOURAVSINGH19 Branch is  not upto date with the latest changes

**Comment by GOURAVSINGH19** [comment]
Ok ai will do it

**Pull request closed without merging**
