### PR TITLE
home button added to all pages

### LINKED ISSUE #316: BUG: Navigation to Home from About page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Navigation to Home from About page is missing 
A small Home icon can be added to easy navigation to home.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by divyansh-2005**
## Related Issue
Fixes #316 

## Description
Navigation to home page from all other pages.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@divyansh-2005 Update the  branch

**Comment by divyansh-2005** [comment]
done

**Comment by divyansh-2005** [comment]
@SUGAM-ARORA please check

**Comment by SUGAM-ARORA** [comment]
@divyansh-2005 Kindly update  branch once again

**Comment by divyansh-2005** [comment]
branch is updated.

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
