### PR TITLE
Fixes #190 : Added Premium Features Option

### LINKED ISSUE #190: Introducing Premium Features
To enrich the website experience, we propose introducing a "Go Pro!" button, offering an array of premium features. Please refer to the attached photo for further details.

go pro

### PR DESCRIPTION
**Pull request by AkshitGarg24**
Fixes #190 

A "Go Pro!" button has been added to the footer section of the website. When clicked, a new web page displaying different options for both the Free and Premium plans will appear. A video has been attached for further reference.

https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/083e3bae-c3ad-4fde-bea4-6fcba22e19a1

**Please label my PR and add my name to the Assignees section before merging the PR.**

Thank you!

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@AkshitGarg24 Impressive work . Just 2 changes needed - 
While we hover on free version  we are not able to select this . By default only pro version is selected. Make it more dynamic.
Secondly - update the branch

**Comment by AkshitGarg24** [comment]
@SUGAM-ARORA, the decision to leave the free option unselectable while hovering is intentional. This design choice ensures that when a new user signs up, they automatically start with the free version. By highlighting the "UniCollab Pro" plan, we draw users' attention to it. I've attached the video from which I got this idea.


https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/9c085697-0453-4f1e-9771-9430b8f1de4b



Please let me know if you have any further suggestions or requests for changes, and I'll make the necessary adjustments. As for your second request, I didn't quite grasp it. Could you please clarify?

Thank you for your understanding!

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA, the decision to leave the free option unselectable while hovering is intentional. This design choice ensures that when a new user signs up, they automatically start with the free version. By highlighting the "UniCollab Pro" plan, we draw users' attention to it. I've attached the video from which I got this idea.
> 
>  Pro.mp4 
> Please let me know if you have any further suggestions or requests for changes, and I'll make the necessary adjustments. As for your second request, I didn't quite grasp it. Could you please clarify?
> 
> Thank you for your understanding!

First request sorted.
Regarding second one- Actually your branch is not up to date with the latest changes . just update your branch. Else good to go.

Try these steps for branch updation.

git checkout main
git pull
git checkout
git merge main
[ ... resolve any conflicts ... ]
git add [files that were conflicted]
git commit
git push

**Review by SUGAM-ARORA — APPROVED** [review]
Looks great

**Pull request merged**
