### PR TITLE
Add Firebase google Login

### LINKED ISSUE #414: Feat: Add Google Login using Firebase
### Describe the feature

Add google login to the login page for better user experience and faster login. This is a basic feature that must be added to the signup and login page. 

### Add ScreenShots

image

@SUGAM-ARORA Please assign this to me 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MinavKaria**
## Related Issue
Fixes #414 

## Description

Add firebase google login, need to add your own firebase keys in `configs/firebase.js`

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by MinavKaria** [comment]
@SUGAM-ARORA Deployment failed bcoz there are no API key added to the firebase.json, This will get fixed if we add api keys. The new contributor can get their firebase keys to use this

**Comment by MinavKaria** [comment]
I'm sure that everything else is fine

**Comment by MinavKaria** [comment]
@SUGAM-ARORA  If you want you can make a temporary firebase api keys and make it public if you are ok with it

**Comment by MinavKaria** [comment]
@SUGAM-ARORA Branch updated

**Comment by MinavKaria** [comment]
Just for the reminder you'll need to add firebase api key in `firebase.json`

**Comment by SUGAM-ARORA** [comment]
> Just for the reminder you'll need to add firebase api key in `firebase.json`

Yes I remember. I will do it alongside merging this pr this week itself

**Comment by MinavKaria** [comment]
> > Just for the reminder you'll need to add firebase api key in `firebase.json`
> 
> Yes I remember. I will do it alongside merging this pr this week itself

@SUGAM-ARORA 

1. First add the API keys after creating the project from project settings 

2. Mainly, Also you must enable Authentication with google in Firebase dashboard

image

click get started

image

Click on google and enable it 

image

You are done ✅

**Comment by MinavKaria** [comment]
@SUGAM-ARORA Please acknowledge

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Please acknowledge

@MinavKaria Update branch . Moreover check the firebase.js . I have already created that with the project requirements. So you can remove yours

**Comment by MinavKaria** [comment]
@SUGAM-ARORA Updated

**Comment by MinavKaria** [comment]
@SUGAM-ARORA Add your api in my `configs/firebase.js` , I have accordingly added the paths in other .js files, is that ok ?

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Add your api in my `configs/firebase.js` , I have accordingly added the paths in other .js files, is that ok ?

@MinavKaria Okay with it. Moreover now error is there on website 
image

Do you have any info regarding that.
How to solve it ??

**Comment by MinavKaria** [comment]
You are hosting the website on firebase ?

**Comment by MinavKaria** [comment]
If yes then use firebase cli to host, it is very easy to host with it and make sure your build folder path is entered correctly

**Comment by SUGAM-ARORA** [comment]
> If yes then use firebase cli to host, it is very easy to host with it and make sure your build folder path is entered correctly

Yes . I am using firebase cli to host .
maybe build folder path issue is there

**Review by SUGAM-ARORA — APPROVED** [review]
Approve

**Comment by Ketanop321** [comment]
can you please tell how to setup your project .

**Comment by Ketanop321** [comment]
@SUGAM-ARORA can you update in Readme.md how to setup this project.

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 UniCollab setup is same as before. Just that at the moment it is not working

**Comment by Ketanop321** [comment]
> @Ketanop321 UniCollab setup is same as before. Just that at the moment it is not working

@SUGAM-ARORA  your vercel link is still not opening

**Comment by SUGAM-ARORA** [comment]
> > @Ketanop321 UniCollab setup is same as before. Just that at the moment it is not working
> 
> will i able to work on my issue right now

Yes you can now work on!

**Pull request merged**
