### PR TITLE
Updated About Page

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #171 

image

I have deleted the other About us file as there were some conflicts.

@SUGAM-ARORA can you please check this and approve it?

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@Hemashree21 This branch is not updated . 
For updation you can do using following steps :

git checkout main
git pull
git checkout <branch>
git merge main
[ ... resolve any conflicts ... ]
git add [files that were conflicted]
git commit
git push

**Comment by Hemashree21** [comment]
> @Hemashree21 This branch is not updated . For updation you can do using following steps :
> 
> git checkout main git pull git checkout git merge main [ ... resolve any conflicts ... ] git add [files that were conflicted] git commit git push

image

It's showing branch up to date

**Comment by SUGAM-ARORA** [comment]
> > @Hemashree21 This branch is not updated . For updation you can do using following steps :
> > git checkout main git pull git checkout git merge main [ ... resolve any conflicts ... ] git add [files that were conflicted] git commit git push
> 
> image
> 
> It's showing branch up to date

@Hemashree21 Still your deployment is not up to date with the latest updates

**Comment by Hemashree21** [comment]
@SUGAM-ARORA I will check it again

**Pull request closed without merging**
