### PR TITLE
Updated Footer

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #178 

image

image

Screenshot 2024-06-03 161443

@SUGAM-ARORA I have updated the footer and made it responsive. please check and let me know if any changes are required

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@Hemashree21 Just update the spacing issue at the bottom . Right now it is quite much . Reduce this

**Comment by Hemashree21** [comment]
which space the space between social media icons and the copyright?

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA which space the space between social media icons and the copyright?

Yes . It is much more than needed.

**Comment by Hemashree21** [comment]
@SUGAM-ARORA I updated it

image

**Comment by SUGAM-ARORA** [comment]
@Hemashree21 Now its better but your branch is still not updated.

**Comment by SUGAM-ARORA** [comment]
Pro feature not visible

**Comment by Hemashree21** [comment]
@SUGAM-ARORA where shall I add the Go Pro button in the Footer? Shall I add it instead of Unicollab since we have the Logo anyway?

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA where shall I add the Go Pro button in the Footer? Shall I add it instead of Unicollab since we have the Logo anyway?

If possible add Go pro at the top (just left of notifications icon)

**Comment by Hemashree21** [comment]
@SUGAM-ARORA I updated it, is this fine?

image

**Comment by Hemashree21** [comment]
@SUGAM-ARORA do you need legal pages for the website, I can work on it. Shall I raise an issue?

**Comment by SUGAM-ARORA** [comment]
@Hemashree21 Any sample ?

**Comment by Hemashree21** [comment]
Screenshot 2024-05-26 113812
Screenshot 2024-05-26 113839

Something like this

**Comment by SUGAM-ARORA** [comment]
> Screenshot 2024-05-26 113812 Screenshot 2024-05-26 113839
> 
> @SUGAM-ARORA Something like this

Works

**Pull request merged**
