### PR TITLE
Elevating User Experience: Footer Refinement, Freelancer Page Fixes, and FAQ Styling

### LINKED ISSUE #421: Feat: Elevating User Experience: Footer Refinement, Freelancer Page Fixes, and FAQ Styling
### Describe the feature

@SUGAM-ARORA There is a problem in footer,hire  a freelancer page and FAQ styling. Kindly assign this issue to me.

### Add ScreenShots
image

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## Related Issue
Fixes #421 

## Description
@SUGAM-ARORA I have made the required changes in the website. Kindly approve.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Ojas-Arora Need to update branch . Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA Done

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA I have done again. Kindly check

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
