### PR TITLE
added scroll feature in top contributor

### LINKED ISSUE #174: top contributor scroll feature
https://github.com/SUGAM-ARORA/UniCollab/assets/146806880/22c50481-1ffc-40c3-9fd2-b96071849839

If you want this feature in top contributor than i will try my best to add this feature this time

### PR DESCRIPTION
**Pull request by Ketanop321**
## Related Issue
Fixes #174 

## Description
[Added a scrolling feature in Top contributor section]

## Type of PR

- [ ✅] Bug fix
- [ ✅] Feature enhancement

## Screenshots / videos (if applicable)
after adding  the feature

https://github.com/SUGAM-ARORA/UniCollab/assets/146806880/b872460d-eb32-42b3-8b00-17148a762da8

## Checklist:
- [✅ ] I have performed a self-review of my code
- [ ✅] I have read and followed the Contribution Guidelines.
- [ ✅] I have tested the changes thoroughly before submitting this pull request.
- [✅ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Ketanop321 Need to update branch . Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by SUGAM-ARORA** [comment]
@Ketanop321 Your branch update changes are not visible

**Comment by Ketanop321** [comment]
@SUGAM-ARORA  i have updated the branch can you look at it , if it is not updated can please guide how could i do it😭

**Comment by SUGAM-ARORA** [comment]
> @Ketanop321 Need to update branch . Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

@Ketanop321 Follow  these steps. Also sometimes changes are been left at vscode only. So on the bottom left there are commits shown check them too and click on them

**Comment by Ketanop321** [comment]
> @Ketanop321 Need to update branch . Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

@SUGAM-ARORA can you check it nowww

**Review by SUGAM-ARORA — APPROVED** [review]
Approve

**Pull request merged**
