### PR TITLE
feat: added issue btns and respective forms

### LINKED ISSUE #7: [FEAT]: Create Issue forms and make the issue options more visually appealing
**Describe the Feature you want to end**

Currently, the issue template for this repo seems to be basic also it is less visually appealing.👇

Screenshot 2023-06-12 at 02-10-25 New Issue · pranjay-poddar_Dev-Geeks

Changes I will make 

Screenshot 2023-06-11 at 01-12-48 New Issue · dakshsinghrathore_htmltut

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**
**Will add issue forms to the respective issues to make it easier for the contributor to raise it.**
Here is an example of how a ***Bug Issue Form*** will look like 👇

Screenshot 2023-06-11 at 01-15-06 New Issue · dakshsinghrathore_htmltut

### PR DESCRIPTION
**Pull request by dakshsinghrathore**
## Related Issue
Fixes #7 

## Description
This PR creates issue buttons and adds respective forms to those buttons.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

image

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Kindly review my PR @SUGAM-ARORA

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@dakshsinghrathore Make sure your branch is up to date with the latest changes

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@dakshsinghrathore  Just do branch updation. 
Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.sh)

**Comment by dakshsinghrathore** [comment]
> @dakshsinghrathore Just do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.sh)

@SUGAM-ARORA my branch is already updated, have created a separate branch for this issue, and it is already in sync.

image

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by dakshsinghrathore** [comment]
@SUGAM-ARORA Kindly merge it.

**Pull request merged**
