### PR TITLE
back navigation button added to pricing page #227

### LINKED ISSUE #227: Add Back Navigation Button to Pricing Page with Matching Color Palette
Hello @SUGAM-ARORA,
There is no back navigation button on the pricing page.
Could you please assign this issue to me, I will add a back button that matches the color palette of the website and navigates to the home page.

### PR DESCRIPTION
**Pull request by mohangolakoti**
## Related Issue
Fixes #227 

## Description
Hello @SUGAM-ARORA,
Iam added a back navigation button to the pricing page that matches the color palette of the website and navigates to the home page.

## Type of PR
- [X] Bug fix

## Screenshots / videos (if applicable)
back-unicollab

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@mohangolakoti Just do branch updation. 
Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.sh%7D)

**Comment by mohangolakoti** [comment]
@SUGAM-ARORA  Iam updated the branch please review the PR

**Comment by SUGAM-ARORA** [comment]
@mohangolakoti You need to again update branch as your previous issue was merged

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
