### PR TITLE
Feat/light and dark toggle

### PR DESCRIPTION
**Pull request by anwesha2002**
## Related Issue
Fixes ##558

## Description
This PR adds new feature of toggle light and dark of the entire website

## Type of PR

- [ ] Bug fix
- [x ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/4f935657-d64d-40d5-9715-94a806662248

## Checklist:
- [ x] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by anwesha2002** [comment]
@SUGAM-ARORA It took a lot of time and effort as I had to change the theme in each of the pages and had to put suitable theme there. so I request to put this under level 3 if possible.

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@anwesha2002 Definately its level 3. You have done great work. Update branch else good to merge

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by anwesha2002** [comment]
> Approved

thanks

**Pull request merged**
