### PR TITLE
Added Rate us Option

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin
I Added Rate Us Page - Solved #442 
Kindly Please go through this PR @SUGAM-ARORA 

https://github.com/SUGAM-ARORA/UniCollab/assets/161804629/b25a385e-3969-4cd6-9398-38b3399b7007

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
Update branch

**Comment by sailaja-adapa** [comment]
@SUGAM-ARORA I updated branch Kindly please look into it

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA I updated branch Kindly please look into it

Failure is there

**Comment by sailaja-adapa** [comment]
@SUGAM-ARORA I Solved them please look into this

**Review by SUGAM-ARORA — APPROVED** [review]
Approve

**Pull request merged**
