### PR TITLE
Fixes #302 : Added Careers Page

### LINKED ISSUE #302: Adding a Career Page
The website currently lacks a dedicated careers page. After thoroughly reviewing the entire codebase, I could not locate any existing implementation for this feature. Therefore, developing and integrating a careers page into the website is necessary.

### PR DESCRIPTION
**Pull request by AkshitGarg24**
Fixes #302 

The Career Page has been created and a video has been included for reference. Currently, I have implemented only the Career Page for type 1. For type 2, as discussed, I will create a separate issue and proceed with its development.

https://github.com/SUGAM-ARORA/UniCollab/assets/153659573/b53e6773-1245-420b-8998-b75a61403119

Please share any suggestions or recommendations you may have.

Thank you!

### CODE REVIEW

**Comment by AkshitGarg24** [comment]
For type 2, #348 has been made.

**Comment by SUGAM-ARORA** [comment]
@AkshitGarg24 Update branch

**Comment by AkshitGarg24** [comment]
Done @SUGAM-ARORA

**Review by SUGAM-ARORA — APPROVED** [review]
Great Work

**Pull request merged**
