### PR TITLE
fix: hover effect

### LINKED ISSUE #476: BUG: Main Page is not responsive for smaller width
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

In the main page the nav bar and side container's like ``stats`` and ``top contributor`` are overflowing for smaller width they can be fixed by using display:flex widht adding a media query on ``925px`` 
Here is the video

https://github.com/SUGAM-ARORA/UniCollab/assets/116784047/30828206-917c-49a9-b684-b1ccaea993fc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### LINKED ISSUE #478: BUG: Hover effect is not working properly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently the hover effect in footer of contact page  ``section-title`` doesnt have proper hover effect like links inside links container 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by upsaurav12**
## Related Issue
Fixes #478 

## Description
Added Transition effect

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by upsaurav12** [comment]
This is second time i am raising new PR because i am getting merge conflicts. Is it good idea to add only files except ``package-lock.json``

**Comment by SUGAM-ARORA** [comment]
> This is second time i am raising new PR because i am getting merge conflicts. Is it good idea to add only files except `package-lock.json`

Then also we get error at later stages since package requirement varies

**Comment by SUGAM-ARORA** [comment]
@upsaurav12 Kindly share what all difficulties u are facing while updating branch

**Comment by upsaurav12** [comment]
@SUGAM-ARORA can you check ??

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
