### PR TITLE
Updated About Page

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #171 

image

@SUGAM-ARORA please check and let me know if any changes are needed

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Hemashree21 Just do one thing update your branch with the latest updates.

**Comment by Hemashree21** [comment]
@SUGAM-ARORA Another About Page has been added

image

What should I do?

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA Another About Page has been added
> 
> image
> 
> What should I do?

But your page is much more impressive . Update the branch and I will merge this

**Comment by SUGAM-ARORA** [comment]
Your About Page looks good

**Comment by SUGAM-ARORA** [comment]
And reopen this pull request @Hemashree21

**Pull request closed without merging**
