### PR TITLE
Sign in form#516

### LINKED ISSUE #516: BUG: Improvment in Signin/Signup form in mobile view
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently the Sign-in/Sign-up page is not responsive for mobile view 

https://github.com/user-attachments/assets/24cea351-3a73-4a60-9c30-f62ca9b8fef4

Improvment in Sign-up/ Sign-in Form

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by upsaurav12**
## Related Issue
Fixes #516

## Description
[Please include a brief description of the changes or features added]
Improved CSS in form page 

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by upsaurav12** [comment]
@SUGAM-ARORA pls review this PR

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@upsaurav12 I think there is merge failure while updating branch . Kindly look into this

**Comment by upsaurav12** [comment]
done!!!!

**Comment by upsaurav12** [comment]
Why this is happening i got merge conflicts then resolved them now deployment failure

**Comment by upsaurav12** [comment]
Now Check this

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
