### PR TITLE
mkdocs site documentation

### LINKED ISSUE #359: DOC: static documentation site
### What's wrong with the existing documentation

there is no documentation ..i d like to propose a static documentation site made using mkdocs 

### Add ScreenShots

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Abhishek-Sood**
## Related Issue
Fixes #359

## Description
documentation site made using mkdocs ready to be deployed

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Abhishek-Sood** [comment]
sir please check if more changes required i m happy to do so :)

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Abhishek-Sood Need to update branch . Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by Abhishek-Sood** [comment]
updated sir :)

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
