### PR TITLE
Wallet Added

### PR DESCRIPTION
**Pull request by tejjhode**
Now users can add points, and all their transactions are visible to them.
Screenshot 2024-05-20 at 4 43 54 PM

### CODE REVIEW

**Comment by tejjhode** [comment]
issue #86

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@tejjhode This is not looking good 
See this link : https://uni-collab-git-fork-tejjhode-main-sugamaroras-projects.vercel.app/

**Comment by tejjhode** [comment]
Ok I will make changes.

**Comment by tejjhode** [comment]
I have some changes on user can add, withdraw and transfer the points

**Comment by tejjhode** [comment]
changes are applied

**Comment by tejjhode** [comment]
Screenshot 2024-05-21 at 8 33 42 AM
changes are applied

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
Sidebar column is shown twice. Else everything looks good.

**Comment by SUGAM-ARORA** [comment]
@tejjhode Any update?

**Pull request closed without merging**
