### PR TITLE
Main page res#476

### LINKED ISSUE #476: BUG: Main Page is not responsive for smaller width
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

In the main page the nav bar and side container's like ``stats`` and ``top contributor`` are overflowing for smaller width they can be fixed by using display:flex widht adding a media query on ``925px`` 
Here is the video

https://github.com/SUGAM-ARORA/UniCollab/assets/116784047/30828206-917c-49a9-b684-b1ccaea993fc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by upsaurav12**
## Related Issue
Fixes #476

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by upsaurav12** [comment]
@SUGAM-ARORA sorry for creating multiple PR's but i am getting merge conflicts every time i am making new PR

**Comment by upsaurav12** [comment]
plw check this PR

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA plw check this PR

There is failure

**Comment by upsaurav12** [comment]
done !!!

**Comment by SUGAM-ARORA** [comment]
> done !!!

Still failure is there

**Comment by upsaurav12** [comment]
HI @SUGAM-ARORA pls check

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
