### PR TITLE
navbar added on top

### LINKED ISSUE #213: Adding navbar on top
**Describe the bug**
 Hello @SUGAM-ARORA , Putting home, about etc all at top of page in navbar section.
Kindly assign me this under GSSoC'24. I'll do my best.

**Screenshot**

Screenshot 2024-06-02 222733

### PR DESCRIPTION
**Pull request by Dilpreet0501**
## Related Issue
Fixes #213

## Description
I have added navbar on top . Kindly review the PR.

## Type of PR

- [x] Feature enhancement

## Screenshots / videos (if applicable)

Screenshot 2024-06-08 205657

Mobile-view

Screenshot 2024-06-08 205749

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@Dilpreet0501 Great work. Just update the branch and then good to go

**Comment by Dilpreet0501** [comment]
I have updated the branch . Kindly review it.

> @Dilpreet0501 Great work. Just update the branch and then good to go

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by SUGAM-ARORA** [comment]
@Dilpreet0501 Level also changed from 2 to 3

**Pull request merged**
