### PR TITLE
Footer unresponsive#477

### LINKED ISSUE #477: BUG: Footer in Contact us page is not responsive for smaller width
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently the footer in ``Contact us`` page is not responsive like some text is breaking

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by upsaurav12**
## Related Issue
Fixes #477 

## Description
[Please include a brief description of the changes or features added]
Added media queries on different width size

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
Still branch not up to date

**Comment by upsaurav12** [comment]
i tried to do but there is no option for doing it

**Comment by upsaurav12** [comment]
this commit has 159 merge conflicts @SUGAM-ARORA

**Comment by upsaurav12** [comment]
@SUGAM-ARORA ``Merge Conflict `` are resolved pls review

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA `Merge Conflict ` are resolved pls review

You neeed to update branch again.

**Comment by upsaurav12** [comment]
can i raise a new PR ??

**Comment by SUGAM-ARORA** [comment]
> can i raise a new PR ??

yes. But have some useful and great contribution

**Comment by upsaurav12** [comment]
i am closing this pr and opening other

**Comment by upsaurav12** [comment]
@SUGAM-ARORA pls check this pr

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA pls check this pr

Need to do again

**Comment by upsaurav12** [comment]
> > @SUGAM-ARORA pls check this pr
> 
> Need to do again 

do you want some chznges in PR ??.

**Comment by SUGAM-ARORA** [comment]
> > > @SUGAM-ARORA pls check this pr
> > 
> > 
> > Need to do again
> 
> do you want some chznges in PR ??.

Just update branch

**Comment by upsaurav12** [comment]
Hi i have updated branch

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
