### PR TITLE
improves blog page ui

### LINKED ISSUE #309: Improve blogs page
Issues with current blog page
1. No proper title or header
2. The blog card width is not fixed. Initially it has a width and when clicks on it the width increased, which not looks good.
3. No hover effects.
4. Expand collapse icons missing.

Please assign this issue to me for the improvement of blog page.

https://github.com/SUGAM-ARORA/UniCollab/assets/139672976/3a06d5b3-b5a2-49da-8287-06768b612461

### PR DESCRIPTION
**Pull request by DharshiBalasubramaniyam**
## Related Issue
Fixes #309 

## Description

1. Added title
2. Add hover effects and animation
3. add expand/collapse icons

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

https://github.com/SUGAM-ARORA/UniCollab/assets/139672976/5e60743e-3bd9-4a53-8e92-9263aa93f0a1

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@DharshiBalasubramaniyam just update the branch

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam just update the branch

Done!

**Comment by SUGAM-ARORA** [comment]
@DharshiBalasubramaniyam Again update the branch

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam Again update the branch

done!

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@DharshiBalasubramaniyam In your deployment the home screen is blank . Kindly check this .
image

**Pull request closed without merging**
