### PR TITLE
Adding Phone Number Authentication

### LINKED ISSUE #518: Feat: Adding Phone Number Authentication
### Describe the feature

@SUGAM-ARORA I want to add Phone Number Authentication Using Firebase. Kindly assign this issue to me.

### Add ScreenShots

Screenshot 2024-07-14 181023

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## Related Issue
Fixes #518 

## Description
@SUGAM-ARORA I have added the Phone number Authentication . Kindly make sure to allow the phone number authentication in the firebase. Kindly review this.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@Ojas-Arora Update branch

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA Done sir

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA Sorry Sir was a mistake

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
