### PR TITLE
[FIXES #162] Implemented Profile Page

### LINKED ISSUE #162: [BUG] Implementing a Profile Page for Users
Implementing a profile page for other developers, will showcase their coding projects, tech stack, and other information.
Would like to work on this task, request you to assign this task under GSSoC '24

prodiles

### PR DESCRIPTION
**Pull request by yashmandi**
#162  Implemented Profile Page

https://github.com/SUGAM-ARORA/UniCollab/assets/132436131/343df203-0ff5-4806-96a3-647753ed13a4

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@yashmandi When we click on Users , the background of Projects and Skills section (white color) is not much impressive

**Comment by SUGAM-ARORA** [comment]
@yashmandi One more thing just sync changes from main

**Comment by yashmandi** [comment]
Screenshot (273)

**Comment by yashmandi** [comment]
Screenshot (273)

**Comment by SUGAM-ARORA** [comment]
> Screenshot (273)

Looks great . Just update the branch and it is good to go now

**Comment by yashmandi** [comment]
> > Screenshot (273)
> 
> Looks great . Just update the branch and it is good to go now

done with changes, kindly check

**Comment by SUGAM-ARORA** [comment]
@yashmandi Still not fully updated. Services and FAQ not workin

**Comment by yashmandi** [comment]
Sorry man, but i cant figure out what's the error, i tried to resolve it though.., i will take a new fork and create a new repo and then will raise new PR

**Comment by SUGAM-ARORA** [comment]
@yashmandi Try the following steps:

git checkout main
git pull
git checkout
git merge main
[ ... resolve any conflicts ... ]
git add [files that were conflicted]
git commit
git push

**Comment by yashmandi** [comment]
> @yashmandi Try the following steps:
> 
> git checkout main git pull git checkout git merge main [ ... resolve any conflicts ... ] git add [files that were conflicted] git commit git push

tried doing it as well, but then the services and FAQ pages are not visible
Screenshot (285)

**Pull request closed without merging**
