### PR TITLE
Filter Buttons Working Now

### PR DESCRIPTION
**Pull request by lakshyajn**
Hey @SUGAM-ARORA 
I have added functionality in filter buttons :)

Thank U for assigning this issue.

I have added filters in Type and Sort By, now by which user can select a particular card they want

Also, I have applied toggling condition on All and Popular button, that is if clicked, they change to pink-blue design and on again clicking it resets to normal

Please merge it and see the results

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@lakshyajn This branch has some conflicts . Kindly resolve them too.

**Comment by lakshyajn** [comment]
Hey @SUGAM-ARORA 
I have deleted one the links of filters and added my own select buttons and those links were not in my code

Screenshot 2024-05-17 225856

I have deleted these lines, but they are still showing, 
What to do about this :/

**Comment by SUGAM-ARORA** [comment]
> Hey @SUGAM-ARORA I have deleted one the links of filters and added my own select buttons and those links were not in my code
> 
> Screenshot 2024-05-17 225856
> 
> I have deleted these lines, but they are still showing, What to do about this 
Have you saved them? Sometimes changes which you have done might not get save.

**Comment by SUGAM-ARORA** [comment]
@lakshyajn Any update

**Pull request closed without merging**
