### PR TITLE
Update the react-router-dom and Fix Footer , 2 issues completed

### LINKED ISSUE #410: Feat:  Update react-router-dom to version 6 and refactor routing logic
### Describe the feature

**Is your feature request related to a problem? Please describe.**
The current routing setup is cumbersome and difficult to manage due to the older version of React Router DOM.

**Describe the solution you'd like**
Update React Router DOM to v6, using createBrowserRouter and RouterProvider for a more efficient routing setup. This will simplify nested routes and improve code maintainability.

**Describe alternatives you've considered**
- Continuing with the older version, which is not sustainable due to deprecated features.
- Using a different routing library, requiring a significant rewrite.

_GSSOC'2024 Contribuitor_

@SUGAM-ARORA Please assign it to me

### Add ScreenShots

image

to new version like this

```
{
          path: '/route/:id',
          element: <ElementNeeded/>
 },
```

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### LINKED ISSUE #413: BUG: Top Contributor Component Hiding Under Footer in Mobile version
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The Top Contributor is box which at the bottom of the mobile version is partially hidden by the footer, that must be fixed.

image

@SUGAM-ARORA Assign this to me 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MinavKaria**
## Related Issue
Fixes #410 
Fixes #413 

## Description

Changed the routing to v6 where all the routes are now present in `configs/router.js` where you need to just add the path and element like 

```
 {
          path: '/route/:id',
          element: <ElementNeeded/>
 },
```

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

Screenshots :

#413

image
image

Footer not overlapping now

## Checklist:
- [X]  I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X]  I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X]  I have commented my code, particularly in hard-to-understand areas.

## Additional context:

Updated the react router dom to version 6 with createBrowserRouter .
and fixed the footer placement

### CODE REVIEW

**Comment by MinavKaria** [comment]
@SUGAM-ARORA Then I'll work on the 3rd Issue then

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@MinavKaria Update branch

**Comment by MinavKaria** [comment]
Updated

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
