### PR TITLE
Alignment Issue

### LINKED ISSUE #417: Feat:Alignment issue
### Describe the feature

@SUGAM-ARORA There is a lot of issue in the alignment of the page. Kindly assign this issue to me.

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## Related Issue
Fixes #417 

## Description
@SUGAM-ARORA I have fixed the alignment issue and styling in the website. Kindly review this.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Ojas-Arora Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by Ojas-Arora** [comment]
@SUGAM-ARORA I see this issue to be level 3 as I have made so many changes.

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA I see this issue to be level 3 as I have made so many changes.

@Ojas-Arora Can you tell if there are any changes except navbar?

**Pull request merged**
