### PR TITLE
Created a Completely Responsive Carreers Page 

### LINKED ISSUE #679: Feat: Want to make the carriers sections fully responsive
### Describe the feature

I want to make the carriers section responsive 

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
## Related Issue
Fixes #679 

## Description
I have created a completely responsive Carrers page 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/890c5a39-ce0b-4db0-9092-4e4d20663a40

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@SUGAM-ARORA Please review it and give lvl 2 if found it suitable for that

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@Ayushmaanagarwal1211 update branch

**Comment by Ayushmaanagarwal1211** [comment]
@SUGAM-ARORA Updated

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
