### PR TITLE
Update Menu.js

### LINKED ISSUE #395: BUG: Icon Link
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Pressing on UC icon wont redirect to the home page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by udayand4s**
## Related Issue
Fixes #395 

## Description
[added feature to go back to home page when unicollab icon is pressed]

## Type of PR

- [X] Feature enhancement

## Checklist:
- [X ] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Thankyou

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@udayand4s Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by udayand4s** [comment]
done

**Comment by SUGAM-ARORA** [comment]
> done

Need to update again

**Comment by udayand4s** [comment]
can you do it now?

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
