### PR TITLE
Added "Website Description" in Footer "Unicolab"

### LINKED ISSUE #329: Add "Website Description" in Footer "Unicolab"
### Describe the feature

Hey @SUGAM-ARORA 

I would like to add website description under unicolab title as the space is empty
Could you please assign this issue to me under GSSOC24 ?

### Add ScreenShots

 - **Current Footer**

image

- **Updated Footer**

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
## Description

Hey @SUGAM-ARORA  issue closes #329 

I have Added "Website Description" in Footer "Unicolab"

image

## Type of PR

- [X] Feature enhancement

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by RadhikaMalpani1702** [comment]
Hey @SUGAM-ARORA 

Please merge PR

**Comment by RadhikaMalpani1702** [comment]
@SUGAM-ARORA 

Please take a look at this PR.

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@RadhikaMalpani1702 Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by RadhikaMalpani1702** [comment]
@SUGAM-ARORA 

update is done

**Comment by RadhikaMalpani1702** [comment]
@SUGAM-ARORA 

Done

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA
> 
> Done

No update visible

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@RadhikaMalpani1702 Do branch updation. Check [Branch Update File](https://github.com/SUGAM-ARORA/UniCollab/blob/main/branchupdate.md)

**Comment by RadhikaMalpani1702** [comment]
Hey @SUGAM-ARORA 

I have updated the branch please merge this as i can't be online at the night time.

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
