### PR TITLE
Implementation of ToDoList Project

### LINKED ISSUE #170: Implementation of TO DO project
**Is your feature request related to a problem? Please describe.**
I saw the project layout in the website, and I got an idea to implement it. This project will be awesome for the website.

**Describe the solution you'd like**
I want to create a website for TO DO list project implemented using HTML, CSS and JavaScript. And link this project to card in the website.

**Describe alternatives you've considered**
I will make it fully functional and easy to use.

### PR DESCRIPTION
**Pull request by saketh-05**
## Related Issue
Fixes #170 

## Description
I have made few changes to several files for correction and added ToDoList project in the Projects folder. Also updated the screenshot of the project. This is a working project and can be used by anyone.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
Screenshot 2024-08-09 083659

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by saketh-05** [comment]
@SUGAM-ARORA Please check this PR.

**Comment by saketh-05** [comment]
@SUGAM-ARORA Please check this deployment issue, As I dont have access to check issue in vercel

**Comment by SUGAM-ARORA** [comment]
@saketh-05 There was a merge failure. Please do any one more commit and then update branch again.

**Comment by saketh-05** [comment]
@SUGAM-ARORA Ok, Thank you. I did it.

**Comment by saketh-05** [comment]
@SUGAM-ARORA I have updated my branch.

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
