### PR TITLE
Added Scroll-to-Top Button #444

### LINKED ISSUE #444: BUG: Improve Scroll-to-Top Button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Hey @SUGAM-ARORA 

I noticed that the current "To the Top" button in the footer is causing extra space and is positioned at the bottom of the footer. For better accessibility and user experience, I propose moving the scroll-to-top button to the bottom right corner of the screen also I will make the button position fixed screen while scrolling and the button will only appear when the user scrolls down a little.

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
## Related Issue
Fixes  #444
## Description
Hey @SUGAM-ARORA 

I have recreated and added a Scroll-to-Top Button as the previous one was not looking good and was stuck to the bottom in the footer cause of extra spaces and inaccessibility affecting user experience

**Changes I Made**

- Created a new scroll-to-top button using `react-style-components`
- The base color is `#ff21bc` and the Hover color `#00ced1`
-  The button only appears when we scroll down a bit 
- After clicking on the button the user will scroll smoothly to the top

image

https://github.com/SUGAM-ARORA/UniCollab/assets/163530398/af358a2e-56ad-4dcb-b0da-fcef196c7049

## Type of PR

- [X] Bug fix
- [X] Feature enhancement

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

If possible Could you please add a level 2 label for this PR?

### CODE REVIEW

**Comment by RadhikaMalpani1702** [comment]
@SUGAM-ARORA Please merge this PR

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
@RadhikaMalpani1702 Update branch

**Comment by RadhikaMalpani1702** [comment]
@SUGAM-ARORA  Update is done

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by RadhikaMalpani1702** [comment]
@SUGAM-ARORA If possible could you please give me a level2 label

**Comment by SUGAM-ARORA** [comment]
@RadhikaMalpani1702 Ya sure .

**Pull request merged**
