### PR TITLE
Format and Enhance Legal Pages: Privacy Policy, Terms and Condition, Licensing

### LINKED ISSUE #616: Format and Enhance Legal Pages: Privacy Policy, Terms and Condition, Licensing
### Describe the feature

Hey @SUGAM-ARORA 

I would like to format and properly align the legal pages in the same adjustment to ensure legal compliance

image

image

image

Additionally, the weight of the text is too heavy, the back-to-home page overlaps the text

image

image

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
## Description
Hey @SUGAM-ARORA 

- issue closes #616 

I have made the legal pages in format 

image

image

image

image

image

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by SUGAM-ARORA — CHANGES_REQUESTED** [review]
Update branch

**Comment by RadhikaMalpani1702** [comment]
@SUGAM-ARORA Update is done

**Comment by SUGAM-ARORA** [comment]
> @SUGAM-ARORA I have updated the branch

Please update again

**Comment by RadhikaMalpani1702** [comment]
@SUGAM-ARORA Done

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Pull request merged**
