### PR TITLE
transformed the CRA code to Vite configuration code

### PR DESCRIPTION
**Pull request by SPraveenKumar-spk**
Migrated project configuration from Create React App (CRA) to Vite

## Summary

This pull request migrates the project configuration from Create React App (CRA) to Vite. Vite offers faster development build times and a more streamlined configuration process. This migration includes updating dependencies, configuration files, and scripts to ensure the project works seamlessly with Vite.

## Changes

1. **Add Vite Configuration:**
   - `vite.config.js` for Vite-specific configuration.
   - `index.html` as the main entry point.
   - Adjusted paths and imports where necessary.

2. **Update Package Scripts:**
   - Changed `start`, `build`, and `test` scripts in `package.json` to use Vite commands.
   - Removed CRA-specific scripts.

3. **Dependency Updates:**
   - Removed `react-scripts` and related CRA dependencies.
   - Added `vite`, `@vitejs/plugin-react`, and other necessary Vite plugins.

4. **Adjust Project Structure:**
   - Updated the project structure to align with Vite's expectations.
   - Moved static assets to the `public` directory.

## How to Test

1. **Install Dependencies:**
   - Run `npm install` to install the updated dependencies.

2. **Run the Development Server:**
   - Use `npm run dev` to start the Vite development server.
   - Verify that the application loads correctly and all functionality works as expected.

3. **Build the Project:**
   - Use `npm run build` to create a production build.
   - Verify that the build process completes successfully and the output is correct.

4. **Run Tests:**
   - Use `npm run test` to run the test suite.
   - Ensure all tests pass without errors.

## Additional Notes

- Updated the LEARN.md file to reflect the changes in development and build processes.
- Please review the changes carefully and test the application thoroughly to ensure no functionality is broken.

Thank you for reviewing this PR. Let me know if you have any questions or need further adjustments.

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@SPraveenKumar-spk Failure is there . Look into this

**Comment by SUGAM-ARORA** [comment]
@SPraveenKumar-spk Any update

**Comment by SPraveenKumar-spk** [comment]
Hi admin i am working on this. Also I would like to inform that, the total codebase will be  changed. The js files will be changed to jsx, vite configuration modules will be used for deployment.

is it ok to change the whole codebase, but the functionality remains the same?

**Comment by SUGAM-ARORA** [comment]
> Hi admin i am working on this. Also I would like to inform that, the total codebase will be changed. The js files will be changed to jsx, vite configuration modules will be used for deployment.
> 
> is it ok to change the whole codebase, but the functionality remains the same?

Till the time there is no effect on functionality I am okay.

**Comment by SUGAM-ARORA** [comment]
You can take your time

**Pull request closed without merging**
