### PR TITLE
Changed Favicon.

### PR DESCRIPTION
**Pull request by SwanandD121**
Changed the favicon from react logo to current website logo.

image

image

### CODE REVIEW

**Comment by SUGAM-ARORA** [comment]
@SwanandD121 Do add the issue number from next time.

**Comment by SUGAM-ARORA** [comment]
#59

**Review by SUGAM-ARORA — APPROVED** [review]
Approved

**Comment by SwanandD121** [comment]
> @SwanandD121 Do add the issue number from next time.

Okay, will do. Thanks for the approval!

**Pull request merged**
